# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b667ef970ebf2da72f5a3cecb87dc9259d13c5601bb10f5ec4d0586c87d8eddedca1b5418f2d49d3dca34d98da63e6923bfec9d331ce7f1779d73640dcfcb22

test:
  secret_key_base: d2a32b61b921408195f68835c4cee9379a7374a5cce03cb33d03a466f940fd7f689ea1e2d203f2bceb91677ac81180fa35617d82c5e2bb0c713e62e3e0bc8a3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
